# Tensors
## This script introduces various ways to create tensors in TensorFlow

First we start with loading TensorFlow and reseting the computational graph.

In [1]:
import tensorflow as tf
from tensorflow.python.framework import ops
ops.reset_default_graph()

### Creating Tensors
TensorFlow has built in function to create tensors for use in variables.  For example, we can create a zero filled tensor of predefined shape using the `tf.zeros()` function as follows.

In [2]:
my_tensor = tf.zeros([1,20])
print(my_tensor)

TensorFlow algorithms need to know which objects are variables and which are constants. The difference between these two objects will be explained later in the chapter. For now we create a variable using the TensorFlow function `tf.Variable()` as follows.

In [3]:
my_var = tf.Variable(tf.zeros([1,20]))
print(my_var)

Let's first start by creating variables of specific shape by declaring our row and column size.

In [4]:
row_dim = 2
col_dim = 3

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.]], dtype=float32)

Here are variables initialized to contain all zeros or ones.

In [5]:
zero_var = tf.Variable(tf.zeros([row_dim, col_dim]))
ones_var = tf.Variable(tf.ones([row_dim, col_dim]))
print(zero_var)
print(ones_var)

### Creating Tensors Based on Other Tensor's Shape
If the shape of a tensor depends on the shape of another tensor, then we can use the TensorFlow built-in functions `ones_like()` or `zeros_like()`.

In [6]:
zero_similar = tf.Variable(tf.zeros_like(zero_var))
ones_similar = tf.Variable(tf.ones_like(ones_var))

print(zero_similar)
print(ones_similar)

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.]], dtype=float32)

### Filling a Tensor with a Constant
Here is how we fill a tensor with a constant.

In [7]:
fill_var = tf.Variable(tf.fill([row_dim, col_dim], -1))
print(fill_var)

We can also create a variable from an array or list of constants.

In [8]:
# Create a variable from a constant
const_var = tf.Variable(tf.constant([8, 6, 7, 5, 3, 0, 9]))
# This can also be used to fill an array:
const_fill_var = tf.Variable(tf.constant(-1, shape=[row_dim, col_dim]))

print(const_var)
print(const_fill_var)

### Creating Tensors Based on Sequences and Ranges
We can also create tensors from sequence generation functions in TensorFlow.  The TensorFlow function `linspace()` and `range()` operate very similar to the python/numpy equivalents.

In [9]:
# linspace in TensorFlow
linear_var = tf.Variable(tf.linspace(start=0.0, stop=1.0, num=3)) # Generates [0.0, 0.5, 1.0] includes the end
print(linear_var)

# Range in TensorFlow
sequence_var = tf.Variable(tf.range(start=6, limit=15, delta=3)) # Generates [6, 9, 12] doesn't include the end
print(sequence_var)

[[ 0.  0.  0.]
 [ 0.  0.  0.]]
[[ 1.  1.  1.]
 [ 1.  1.  1.]]


### Random Number Tensors
We can also initialize tensors that come from random numbers like the following.

In [10]:
rnorm_var = tf.random.normal([row_dim, col_dim], mean=0.0, stddev=1.0)
runif_var = tf.random.uniform([row_dim, col_dim], minval=0, maxval=4)

print(rnorm_var)
print(runif_var)

[[ 1.  1.  1.]
 [ 1.  1.  1.]]
[[ 0.  0.  0.]
 [ 0.  0.  0.]]


### Visualizing the Variable Creation in TensorBoard
To visualize the creation of variables in Tensorboard (covered in more detail in Chapter 11), we will reset the computational graph and create a global initializing operation.

In [11]:
# Reset graph
ops.reset_default_graph()

# Create variable
my_var = tf.Variable(tf.zeros([1,20]))

# Initialize graph writer:
writer = tf.summary.create_file_writer("/tmp/variable_logs")

with writer.as_default():
  for step in range(100):
    # other model code would go here
    tf.summary.scalar("my_metric", 0.5, step=step)
    writer.flush()

[[-1 -1 -1]
 [-1 -1 -1]]


We now run the following command in our command prompt:

`tensorboard --logdir=/tmp/variable_logs`

And it will tell us the URL we can navigate our browser to to see Tensorboard. The default should be:

`http://0.0.0.0:6006/`