# Tensors
## This script introduces various ways to create tensors in TensorFlow

First we start with loading TensorFlow and reseting the computational graph.

In [1]:
import tensorflow as tf
from tensorflow.python.framework import ops
ops.reset_default_graph()

### Creating Tensors
TensorFlow has built in function to create tensors for use in variables.  For example, we can create a zero filled tensor of predefined shape using the `tf.zeros()` function as follows.

In [2]:
my_tensor = tf.zeros([1,20])
my_tensor

<tf.Tensor: shape=(1, 20), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]], dtype=float32)>

TensorFlow algorithms need to know which objects are variables and which are constants. The difference between these two objects will be explained later in the chapter. For now we create a variable using the TensorFlow function `tf.Variable()` as follows.

In [3]:
my_var = tf.Variable(tf.zeros([1,20]))
my_var

<tf.Variable 'Variable:0' shape=(1, 20) dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]], dtype=float32)>

Let's first start by creating variables of specific shape by declaring our row and column size.

In [4]:
row_dim = 2
col_dim = 3

Here are variables initialized to contain all zeros or ones.

In [5]:
zero_var = tf.Variable(tf.zeros([row_dim, col_dim]))
zero_var

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [6]:
ones_var = tf.Variable(tf.ones([row_dim, col_dim]))
ones_var

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

### Creating Tensors Based on Other Tensor's Shape
If the shape of a tensor depends on the shape of another tensor, then we can use the TensorFlow built-in functions `ones_like()` or `zeros_like()`.

In [7]:
zero_similar = tf.Variable(tf.zeros_like(zero_var))
zero_similar

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [8]:
ones_similar = tf.Variable(tf.ones_like(ones_var))
ones_similar

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

### Filling a Tensor with a Constant
Here is how we fill a tensor with a constant.

In [9]:
fill_var = tf.Variable(tf.fill([row_dim, col_dim], -1))
fill_var

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[-1, -1, -1],
       [-1, -1, -1]], dtype=int32)>

We can also create a variable from an array or list of constants.

In [10]:
# Create a variable from a constant
const_var = tf.Variable(tf.constant([8, 6, 7, 5, 3, 0, 9]))
const_var

<tf.Variable 'Variable:0' shape=(7,) dtype=int32, numpy=array([8, 6, 7, 5, 3, 0, 9], dtype=int32)>

In [11]:
# This can also be used to fill an array:
const_fill_var = tf.Variable(tf.constant(-1, shape=[row_dim, col_dim]))
const_fill_var

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[-1, -1, -1],
       [-1, -1, -1]], dtype=int32)>

### Creating Tensors Based on Sequences and Ranges
We can also create tensors from sequence generation functions in TensorFlow.  The TensorFlow function `linspace()` and `range()` operate very similar to the python/numpy equivalents.

In [12]:
# linspace in TensorFlow
linear_var = tf.Variable(tf.linspace(start=0.0, stop=1.0, num=3)) # Generates [0.0, 0.5, 1.0] includes the end
linear_var

<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([0. , 0.5, 1. ], dtype=float32)>

In [13]:
# Range in TensorFlow
sequence_var = tf.Variable(tf.range(start=6, limit=15, delta=3)) # Generates [6, 9, 12] doesn't include the end
sequence_var

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([ 6,  9, 12], dtype=int32)>

### Random Number Tensors
We can also initialize tensors that come from random numbers like the following.

In [14]:
rnorm_var = tf.random.normal([row_dim, col_dim], mean=0.0, stddev=1.0)
rnorm_var

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.5645275 ,  0.92723453, -0.41099927],
       [-0.03344633,  1.04952   , -0.7480582 ]], dtype=float32)>

In [15]:
runif_var = tf.random.uniform([row_dim, col_dim], minval=0, maxval=4)
runif_var

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.9243274 , 0.6473565 , 1.1343379 ],
       [0.45193386, 2.147493  , 0.5621824 ]], dtype=float32)>

### Visualizing the Variable Creation in TensorBoard
To visualize the creation of variables in Tensorboard (covered in more detail in Chapter 11), we will reset the computational graph and create a global initializing operation.

In [16]:
# Reset graph
ops.reset_default_graph()

# Create variable
my_var = tf.Variable(tf.zeros([1,20]))

# Initialize graph writer:
writer = tf.summary.create_file_writer("/tmp/variable_logs")

with writer.as_default():
  for step in range(100):
    # other model code would go here
    tf.summary.scalar("my_metric", 0.5, step=step)
    writer.flush()

We now run the following command in our command prompt:

`tensorboard --logdir=/tmp/variable_logs`

And it will tell us the URL we can navigate our browser to to see Tensorboard. The default should be:

`http://0.0.0.0:6006/`