# Matrices and Matrix Operations

This function introduces various ways to create
matrices and how to use them in TensorFlow

In [2]:
import numpy as np
import tensorflow as tf
from tensorflow.python.framework import ops
ops.reset_default_graph()

In [3]:
identity_matrix = tf.Variable(tf.ones([3]))

2x3 random norm matrix:

In [4]:
A = tf.random.normal([2, 3], mean=0.0, stddev=1.0)
A

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-1.4230685 , -0.5552142 ,  0.6566152 ],
       [ 0.14955139,  0.06151237,  0.13585317]], dtype=float32)>

2x3 constant matrix:

In [5]:
B = tf.fill([2,3], 5.0)
B

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[5., 5., 5.],
       [5., 5., 5.]], dtype=float32)>

3x2 random uniform matrix:

In [6]:
C = tf.random.uniform([3,2])
C

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.13532615, 0.25329542],
       [0.08515978, 0.28453267],
       [0.61491835, 0.33309984]], dtype=float32)>

Create matrix from np array:

In [7]:
D = tf.convert_to_tensor(np.array([[1., 2., 3.], [-3., -7., -1.], [0., 5., -2.]]))
D

<tf.Tensor: shape=(3, 3), dtype=float64, numpy=
array([[ 1.,  2.,  3.],
       [-3., -7., -1.],
       [ 0.,  5., -2.]])>

### Matrix Operations

Matrix addition/subtraction:

In [8]:
tf.math.add(A,B, name="E")

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[3.5769315, 4.4447856, 5.6566153],
       [5.1495514, 5.0615125, 5.1358533]], dtype=float32)>

Matrix Multiplication:

In [9]:
tf.math.multiply(B, identity_matrix)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[5., 5., 5.],
       [5., 5., 5.]], dtype=float32)>

Matrix Transpose:

In [10]:
tf.transpose(C)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.13532615, 0.08515978, 0.61491835],
       [0.25329542, 0.28453267, 0.33309984]], dtype=float32)>

Matrix Determinant:

In [11]:
tf.linalg.det(D)

<tf.Tensor: shape=(), dtype=float64, numpy=-37.99999999999999>

Matrix Inverse:

In [12]:
tf.linalg.inv(D)

<tf.Tensor: shape=(3, 3), dtype=float64, numpy=
array([[-0.5       , -0.5       , -0.5       ],
       [ 0.15789474,  0.05263158,  0.21052632],
       [ 0.39473684,  0.13157895,  0.02631579]])>

Eigenvalues and Eigenvectors:  We use `tf.linalg.eig()` function, which returns two objects, first one is an array of eigenvalues, the second is a matrix of the eigenvectors.

In [16]:
eigen_values, eigen_vectors = tf.linalg.eig(D)

print(eigen_values)
print(eigen_vectors)

tf.Tensor(
[-0.7845763-2.30075186e+00j -0.7845763+2.30075186e+00j
 -6.4308474+2.22044605e-16j], shape=(3,), dtype=complex128)
tf.Tensor(
[[ 0.3808758 -0.63383659j  0.07100542-0.7360526j  -0.07301314-0.09862827j]
 [-0.18195173+0.25193768j -0.0036604 +0.31075011j -0.39163158-0.52902728j]
 [-0.59136639-0.08301544j  0.52469353+0.28513589j  0.44193756+0.59698206j]], shape=(3, 3), dtype=complex128)
